/**
 * Texte der Oberfläche (P25.2): je Schlüssel [Deutsch, Spanisch]; Funktionen bekommen Parameter.
 * Gelesen über t()/translate() in i18n.js (Rückfall Deutsch). Inhalte (Aufgaben, Themen, Gesprächsszenarien) und
 * Erklärungen (explain.js, Erklärungssprache) stehen nicht hier.
 */

/* eslint-disable quote-props */
export const STRINGS = Object.freeze({
  // ---------------------------------------------------------------- Rahmen und Navigation
  "app.starting": ["App wird gestartet …", "Iniciando la app …"],
  "app.offline_badge": ["Offline – alles funktioniert weiter, gespeichert wird lokal.", "Sin conexión: la app sigue funcionando y guarda en el dispositivo."],
  "app.skip": ["Zum Inhalt springen", "Ir al contenido"],
  "app.no_storage": ["Speichern ist in diesem Browser nicht möglich: Dein Fortschritt geht beim Schließen verloren.",
    "Este navegador no permite guardar: tu progreso se perderá al cerrarlo."],
  "app.start_failed": ["Die App konnte gerade nicht gestartet werden.", "No se ha podido iniciar la app."],
  "app.content_failed": ["Die Lerninhalte ließen sich nicht laden. Bitte versuche es noch einmal.",
    "No se han podido cargar los contenidos. Inténtalo de nuevo."],
  "app.offline_first": ["Du bist offline und die App wurde auf diesem Gerät noch nicht vollständig geladen. Verbinde dich einmal mit dem Internet.",
    "Estás sin conexión y la app aún no se ha cargado por completo en este dispositivo. Conéctate a internet una vez."],
  "app.now_learning": [(name) => `Du lernst jetzt ${name}.`, (name) => `Ahora aprendes ${name}.`],
  "app.now_learner": [(name) => `Jetzt lernt ${name}.`, (name) => `Ahora aprende ${name}.`],
  "app.home_label": [(app) => `${app} – Startseite`, (app) => `${app} – Inicio`],
  "app.active_user": ["Aktiver Nutzer (im Profil wechseln)", "Perfil activo (cámbialo en Perfil)"],
  "app.active_user_sr": ["Aktiver Nutzer: ", "Perfil activo: "],
  "app.learning_language": ["Lernsprache", "Idioma que aprendes"],
  "app.page_failed": ["Diese Seite konnte gerade nicht geladen werden.", "No se ha podido cargar esta página."],
  "app.session_failed": ["Die Lernsession konnte gerade nicht geladen werden.", "No se ha podido cargar la sesión."],
  "app.other_tab": ["Die App ist noch in einem anderen Tab geöffnet. Schließe ihn und versuche es erneut.",
    "La app sigue abierta en otra pestaña. Ciérrala e inténtalo de nuevo."],
  "app.delete_failed": ["Die Daten konnten nicht gelöscht werden.", "No se han podido borrar los datos."],
  "app.sw_unsupported": ["nicht unterstützt", "no compatible"],
  "app.sw_ready": ["bereit", "lista"],
  "app.sw_setup": ["wird eingerichtet", "preparándose"],
  "app.new_version": ["Eine neue Version ist bereit.", "Hay una versión nueva."],
  "app.reload": ["Neu laden", "Recargar"],
  "app.offline_ready": ["Die App ist jetzt offline verfügbar.", "La app ya funciona sin conexión."],
  "app.no_data": ["noch keine Daten", "aún sin datos"],
  "work.session": ["eine offene Session", "una sesión abierta"],
  "work.conversation": ["ein laufendes Gespräch", "una conversación en curso"],
  "work.assessment": ["eine laufende Einstufung", "una prueba de nivel en curso"],
  "work.and": [" und ", " y "],
  "work.title": [(name, parts) => `${name} hat ${parts}`, (name, parts) => `${name} tiene ${parts}`],
  "work.language": ["Das bleibt bei dieser Sprache. Was soll damit geschehen?", "Se queda en este idioma. ¿Qué hacemos con ello?"],
  "work.learner": ["Das bleibt bei diesem Nutzer. Was soll damit geschehen?", "Se queda en este perfil. ¿Qué hacemos con ello?"],
  "work.pause": ["Pausieren und wechseln", "Pausar y cambiar"],
  "work.abandon": ["Beenden und wechseln", "Terminar y cambiar"],
  "nav.home": ["Start", "Inicio"],
  "nav.learn": ["Lernen", "Aprender"],
  "nav.practice": ["Üben", "Practicar"],
  "nav.progress": ["Fortschritt", "Progreso"],
  "nav.profile": ["Profil", "Perfil"],

  // ---------------------------------------------------------------- Allgemein
  "common.cancel": ["Abbrechen", "Cancelar"],
  "common.retry": ["Erneut versuchen", "Reintentar"],
  "common.error": ["Das hat gerade nicht geklappt.", "Algo ha fallado."],
  "common.loading": ["Wird geladen …", "Cargando …"],
  "common.back_home": ["Zur Startseite", "Ir al inicio"],
  "common.save": ["Speichern", "Guardar"],
  "common.saved": ["Gespeichert.", "Guardado."],
  "common.save_failed": ["Konnte nicht gespeichert werden.", "No se ha podido guardar."],
  "common.minutes": [(n) => `${n} Minuten`, (n) => `${n} minutos`],
  "common.exercises": [(n) => (n === 1 ? "1 Übung" : `${n} Übungen`), (n) => (n === 1 ? "1 ejercicio" : `${n} ejercicios`)],

  // ---------------------------------------------------------------- Aufgabe, Antwort, Hören
  "c.challenge": ["Challenge", "Reto"],
  "c.about": [(t) => `ca. ${t}`, (t) => `aprox. ${t}`],
  "c.focus": ["Schwerpunkt: ", "Enfoque: "],
  "c.task": ["Aufgabe", "Tarea"],
  "c.goal": ["Ziel: ", "Objetivo: "],
  "c.min_words": [(n) => `Mindestens ${n} Wörter.`, (n) => `Mínimo ${n} palabras.`],
  "c.gap": ["Lücke", "Hueco"],
  "c.reply_message": ["Antworte in einer Nachricht.", "Responde en un mensaje."],
  "c.check": ["Prüfen", "Comprobar"],
  "c.checking": ["Wird geprüft …", "Comprobando …"],
  "c.kbd_long": ["Strg/⌘ + Enter zum Prüfen", "Ctrl/⌘ + Intro para comprobar"],
  "c.kbd_short": ["Enter zum Prüfen", "Intro para comprobar"],
  "c.skip_ai": ["KI-Hinweise überspringen", "Saltar indicaciones de IA"],
  "c.word_count": [(n, min) => `${n} / ${min} Wörter`, (n, min) => `${n} / ${min} palabras`],
  "c.save_failed": ["Die Antwort konnte gerade nicht gespeichert werden. Bitte versuche es noch einmal.",
    "No se ha podido guardar la respuesta. Inténtalo de nuevo."],
  "c.your_answer": ["Deine Antwort", "Tu respuesta"],
  "c.choose_answer": ["Wähle eine Antwort", "Elige una respuesta"],
  "c.speak": ["Sprechen", "Hablar"],
  "c.recognizing": ["Wird erkannt …", "Reconociendo …"],
  "c.recognizing_local": ["Wird lokal erkannt …", "Reconociendo en el dispositivo …"],
  "c.not_understood": ["Nichts verstanden. Versuche es noch einmal oder tippe.", "No se ha entendido nada. Inténtalo otra vez o escribe."],
  "c.unsure": ["Unsicher erkannt – bitte prüfe den Text, bevor du ihn abschickst.", "Reconocimiento dudoso: revisa el texto antes de enviarlo."],
  "c.recognized": ["Erkannt. Du kannst den Text noch korrigieren.", "Reconocido. Aún puedes corregir el texto."],
  "c.bad_audio": [(m) => `Die Aufnahme war nicht verwendbar (${m}).`, (m) => `La grabación no se ha podido usar (${m}).`],
  "c.stt_off": ["Spracherkennung gerade nicht möglich. Bitte tippe deine Antwort.", "El reconocimiento de voz no está disponible. Escribe tu respuesta."],
  "c.mic_denied": ["Das Mikrofon ist nicht erlaubt. Du kannst deine Antwort tippen.", "El micrófono no está permitido. Puedes escribir tu respuesta."],
  "c.no_mic": ["Kein Mikrofon verfügbar. Du kannst deine Antwort tippen.", "No hay micrófono. Puedes escribir tu respuesta."],
  "c.stop": ["Stopp", "Parar"],
  "c.stop_s": [(s) => `Stopp (${s} s)`, (s) => `Parar (${s} s)`],
  "c.recording": [(max) => `Aufnahme läuft (höchstens ${max} s). Die Aufnahme bleibt auf diesem Gerät.`,
    (max) => `Grabando (máximo ${max} s). La grabación no sale de este dispositivo.`],
  "c.ai_unavailable": ["KI-Zusatzanalyse gerade nicht erreichbar – bewertet wurde mit den Regeln.", "El análisis de IA no está disponible; se ha evaluado con las reglas."],
  "c.ai_timeout": ["KI-Zusatzanalyse hat zu lange gebraucht – bewertet wurde mit den Regeln.", "El análisis de IA ha tardado demasiado; se ha evaluado con las reglas."],
  "c.ai_invalid": ["KI-Zusatzanalyse lieferte nichts Verwertbares – bewertet wurde mit den Regeln.", "El análisis de IA no ha dado nada útil; se ha evaluado con las reglas."],
  "c.ai_skipped": ["KI-Zusatzhinweise übersprungen.", "Indicaciones de IA omitidas."],
  "c.ai_hints": [(n) => `KI-Hinweise, unbestätigt (${n})`, (n) => `Indicaciones de IA, sin confirmar (${n})`],
  "c.ai_note": ["Lokales Sprachmodell. Ergänzung ohne Einfluss auf Bewertung und Lernstand.", "Modelo de lenguaje local. Complemento sin efecto en la evaluación ni en el progreso."],
  "c.ai": ["KI", "IA"],
  "l.not_heard": ["Noch nicht gehört", "Aún sin escuchar"],
  "l.listen": ["Anhören", "Escuchar"],
  "l.replay": ["Noch einmal von vorn", "Otra vez desde el principio"],
  "l.cannot_play": ["Die Aufnahme lässt sich gerade nicht abspielen.", "No se puede reproducir la grabación."],
  "l.heard": [(n) => `${n}× gehört`, (n) => `Escuchado ${n} ${n === 1 ? "vez" : "veces"}`],
  "l.pause": ["Pause", "Pausa"],
  "l.playing": [(heard) => `${heard} · läuft`, (heard) => `${heard} · reproduciendo`],
  "l.continue": ["Weiter anhören", "Seguir escuchando"],
  "l.help_note": ["Mit Hilfe zählt deine Antwort weniger als Hörverstehen ohne Hilfe.", "Con ayuda, tu respuesta cuenta menos que sin ayuda."],
  "l.dont_know": ["Nichts verstanden", "No he entendido nada"],
  "l.skip": ["Überspringen", "Saltar"],
  "l.recording": ["Aufnahme", "Grabación"],
  "l.speakers": [(n) => `${n} Sprecher`, (n) => `${n} hablantes`],
  "l.refers": ["Bezieht sich auf: ", "Se refiere a: "],
  "l.help": ["Hilfe: ", "Ayuda: "],
  "l.source": ["Quelle", "Fuente"],
  "l.dev_only": [" nur Entwicklung", " solo desarrollo"],

  // ---------------------------------------------------------------- Startseite
  "home.welcome": ["Schön, dass du da bist.", "Qué bien que estés aquí."],
  "home.soon": ["Inhalte in Vorbereitung", "Contenido en preparación"],
  "home.no_content": [(n) => `Für ${n} gibt es noch keine Übungen`, (n) => `Aún no hay ejercicios de ${n.toLowerCase()}`],
  "home.no_content_text": ["Die Sprache ist vorgemerkt und hat ein eigenes, leeres Lernprofil. Übungen, Gespräche und die Einstufung kommen mit dem Inhaltspaket dieser Sprache.",
    "El idioma está guardado y tiene su propio perfil vacío. Los ejercicios, las conversaciones y la prueba de nivel llegarán con su paquete de contenidos."],
  "home.no_content_other": ["Deine anderen Sprachen sind davon nicht betroffen: Fortschritt und Fehler bleiben getrennt.",
    "Tus otros idiomas no se ven afectados: el progreso y los errores se mantienen separados."],
  "home.to_languages": ["Zu meinen Sprachen", "Ir a mis idiomas"],
  "home.assess_resume": ["Einstufung fortsetzen", "Continuar la prueba de nivel"],
  "home.assess_start": ["Einstufung machen", "Hacer la prueba de nivel"],
  "home.assess_again": ["Neu einstufen (empfohlen)", "Repetir la prueba (recomendado)"],
  "home.your_language": [(n) => `Dein ${n}`, (n) => `Tu ${n.toLowerCase()}`],
  "home.profile": ["Profil", "Perfil"],
  "home.not_enough": ["Noch nicht genügend Daten für eine verlässliche Einstufung.", "Aún no hay datos suficientes para una estimación fiable."],
  "home.quick": ["Schnellzugriff", "Acceso rápido"],
  "home.speak": ["Sprechen", "Hablar"],
  "home.review": ["Kurz wiederholen", "Repaso rápido"],
  "home.assessment": ["Einstufung", "Prueba de nivel"],
  "home.goal_reached": [(m, g) => `Tagesziel erreicht: ${m} von ${g} Minuten.`, (m, g) => `Objetivo diario cumplido: ${m} de ${g} minutos.`],
  "home.today_of": [(m, g) => `Heute ${m} von ${g} Minuten.`, (m, g) => `Hoy ${m} de ${g} minutos.`],
  "home.goal": [(g) => `Dein Tagesziel: ${g} Minuten.`, (g) => `Tu objetivo diario: ${g} minutos.`],
  "home.paused": ["Pausiert", "En pausa"],
  "home.running": ["Läuft gerade", "En curso"],
  "home.your_session": ["Deine Session", "Tu sesión"],
  "home.done_of": [(c, n) => `${c} von ${n} Übungen erledigt.`, (c, n) => `${c} de ${n} ejercicios hechos.`],
  "home.session_progress": ["Fortschritt der Session", "Progreso de la sesión"],
  "home.resume": ["Fortsetzen", "Continuar"],
  "home.continue": ["Weiter lernen", "Seguir aprendiendo"],
  "home.conv_paused": ["Pausiertes Gespräch", "Conversación en pausa"],
  "home.conv_open": ["Offenes Gespräch", "Conversación abierta"],
  "home.conv_progress": [(a, m) => `${a} Antworten, noch etwa ${m} Min.`, (a, m) => `${a} respuestas, quedan unos ${m} min.`],
  "home.conv_resume": ["Gespräch fortsetzen", "Continuar la conversación"],
  "home.no_session": ["Gerade keine Session möglich", "Ahora no hay sesión posible"],
  "home.no_session_text": ["Für diese Länge gibt es keine passenden Übungen. Wähle eine andere Länge.", "No hay ejercicios adecuados para esta duración. Elige otra."],
  "home.choose_length": ["Länge wählen", "Elegir duración"],
  "home.learn_now": ["Jetzt lernen", "Aprender ahora"],
  "home.after_assessment": ["Nach deiner Einstufung", "Tras tu prueba de nivel"],
  "home.no_history": ["Noch keine Lernhistorie", "Aún sin historial"],
  "home.next_session": ["Deine nächste Session", "Tu próxima sesión"],
  "home.first_session": ["Starte deine erste Session", "Empieza tu primera sesión"],
  "home.first_after": ["Sie baut auf deiner Einstufung auf. Danach plant die App jede Session neu, nach deinen Antworten, Fehlern und Wiederholungen.",
    "Se basa en tu prueba de nivel. Después, la app planifica cada sesión según tus respuestas, errores y repasos."],
  "home.first_before": ["Die erste Session zeigt, wo du stehst. Danach plant die App gezielt nach deinen Fehlern und Wiederholungen.",
    "La primera sesión muestra dónde estás. Después, la app planifica según tus errores y repasos."],
  "home.start": ["Starten", "Empezar"],
  "home.other_length": ["Andere Länge wählen", "Elegir otra duración"],
  "home.how": ["So lernst du hier", "Así aprendes aquí"],
  "home.how1": ["Jede Session wird neu geplant. ", "Cada sesión se planifica de nuevo. "],
  "home.how1_text": ["Aus deinen Fehlern, fälligen Wiederholungen und neuen Themen.", "A partir de tus errores, los repasos pendientes y temas nuevos."],
  "home.how2": ["Du schreibst selbst. ", "Escribes tú. "],
  "home.how2_text": ["Freie Antworten zählen mehr als Ankreuzen, denn so wird Wissen zu Können.", "Las respuestas libres cuentan más que marcar opciones: así el saber se convierte en capacidad."],
  "home.how3": ["Alles bleibt auf diesem Gerät. ", "Tus datos se quedan en este dispositivo. "],
  "home.how3_text": ["Die Bewertung läuft lokal, auch offline, ohne Cloud und ohne KI-Kosten.", "La evaluación es local, también sin conexión, sin nube y sin costes de IA."],
  "home.week_trend": [(a, p) => `${a} Übungen in 7 Tagen (davor ${p}).`, (a, p) => `${a} ejercicios en 7 días (antes ${p}).`],
  "home.week_count": [(a) => `${a} Übungen in den letzten 7 Tagen.`, (a) => `${a} ejercicios en los últimos 7 días.`],
  "home.today": ["Heute", "Hoy"],
  "home.streak_title": ["Lerntage in Folge", "Días seguidos aprendiendo"],
  "home.streak": [(n) => (n === 1 ? "1 Tag in Folge" : `${n} Tage in Folge`), (n) => (n === 1 ? "1 día seguido" : `${n} días seguidos`)],
  "home.daily_goal": ["Tagesziel", "Objetivo diario"],
  "home.with_errors": [(n) => `davon ${n} mit Fehlern`, (n) => `${n} con errores`],
  "home.all_correct": ["alle ohne Fehler", "sin errores"],
  "home.none_today": ["Heute noch keine Übung.", "Hoy aún no hay ejercicios."],
  "home.this_week": ["Diese Woche", "Esta semana"],
  "home.needs": ["Aktueller Lernbedarf", "Qué toca ahora"],
  "home.weekdays": [["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"], ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"]],


  // ---------------------------------------------------------------- Lernen und Session
  "learn.open": ["Du hast eine offene Session", "Tienes una sesión abierta"],
  "learn.open_text": [(c, n) => `${c} von ${n} Übungen erledigt. Eine neue Session gibt es, wenn diese fertig oder beendet ist.`,
    (c, n) => `${c} de ${n} ejercicios hechos. Habrá una sesión nueva cuando esta termine o la finalices.`],
  "learn.start": ["Session starten", "Empezar sesión"],
  "learn.planning": ["Session wird geplant …", "Planificando la sesión …"],
  "learn.none": ["Für diese Länge gibt es gerade keine passenden Übungen.", "Ahora no hay ejercicios adecuados para esta duración."],
  "learn.preview_failed": ["Die Vorschau konnte gerade nicht berechnet werden.", "No se ha podido calcular la vista previa."],
  "learn.lead": ["Die App plant jede Session neu aus deinen Fehlern, fälligen Wiederholungen und neuen Themen.",
    "La app planifica cada sesión a partir de tus errores, los repasos pendientes y temas nuevos."],
  "learn.time": ["Wie viel Zeit hast du?", "¿Cuánto tiempo tienes?"],
  "learn.length": ["Länge der Session", "Duración de la sesión"],
  "learn.start_failed": ["Die Lernsession konnte gerade nicht gestartet werden.", "No se ha podido iniciar la sesión."],
  "session.title": ["Session", "Sesión"],
  "session.none": ["Keine laufende Session", "No hay ninguna sesión en curso"],
  "session.none_text": ["Starte eine neue Session, wenn du lernen möchtest.", "Empieza una sesión nueva cuando quieras aprender."],
  "session.pause_label": ["Session pausieren", "Pausar la sesión"],
  "session.pause_failed": ["Die Session konnte gerade nicht pausiert werden.", "No se ha podido pausar la sesión."],
  "session.end_label": ["Session beenden", "Terminar la sesión"],
  "session.end": ["Beenden", "Terminar"],
  "session.noted": ["Notiert, kein Fehler. Nutze eine Hilfe oder antworte, so gut es geht.", "Anotado, no cuenta como error. Usa una ayuda o responde lo mejor que puedas."],
  "session.to_summary": ["Zur Auswertung", "Ver resultado"],
  "session.next": ["Weiter", "Siguiente"],
  "session.resume_failed": ["Die Session konnte gerade nicht fortgesetzt werden.", "No se ha podido continuar la sesión."],
  "session.paused_text": [(c, n) => `${c} von ${n} Übungen erledigt. Die Pausenzeit zählt nicht als Lernzeit.`,
    (c, n) => `${c} de ${n} ejercicios hechos. El tiempo en pausa no cuenta como tiempo de estudio.`],
  "session.end_q": ["Session beenden?", "¿Terminar la sesión?"],
  "session.end_text": ["Deine bereits gemachten Übungen bleiben gespeichert. Die übrigen Aufgaben verfallen.",
    "Los ejercicios que ya has hecho quedan guardados. Los demás se descartan."],
  "session.keep": ["Weiterlernen", "Seguir aprendiendo"],
  "session.end_failed": ["Die Session konnte gerade nicht beendet werden.", "No se ha podido terminar la sesión."],
  "session.ended": ["Session beendet.", "Sesión terminada."],
  "session.completed": ["Session abgeschlossen!", "¡Sesión completada!"],
  "session.saved": ["Deine bereits gemachten Übungen wurden gespeichert.", "Los ejercicios que has hecho se han guardado."],
  "session.kept_going": ["Gut, dass du drangeblieben bist.", "Bien hecho por no rendirte."],
  "session.strong": ["Stark.", "Muy bien."],
  "session.saved_next": ["Alles ist gespeichert und fließt in deine nächste Session ein.", "Está guardado y se tendrá en cuenta en tu próxima sesión."],
  "session.exercises": ["Übungen", "Ejercicios"],
  "session.of": [(n) => ` von ${n}`, (n) => ` de ${n}`],
  "session.correct": ["Richtig", "Correctos"],
  "session.with_errors": ["Mit Fehlern", "Con errores"],
  "session.open": ["Offen", "Abiertos"],
  "session.time": ["Lernzeit", "Tiempo"],
  "session.more": [(n) => `+ ${n} weitere`, (n) => `+ ${n} más`],
  "session.work_on": ["Daran arbeiten wir weiter", "En esto seguimos trabajando"],
  "session.failures": [(f, s) => ` – ${f}× nicht gelungen${s ? `, ${s}× gelungen` : ""}`,
    (f, s) => ` – ${f} ${f === 1 ? "fallo" : "fallos"}${s ? `, ${s} ${s === 1 ? "acierto" : "aciertos"}` : ""}`],
  "session.see_progress": ["Fortschritt ansehen", "Ver progreso"],


  // ---------------------------------------------------------------- Üben
  "practice.lead": ["Einzelne Übungen nach Thema. Für den besten Lerneffekt plant „Lernen“ die Mischung für dich.",
    "Ejercicios sueltos por tema. Para aprender mejor, «Aprender» planifica la combinación por ti."],
  "practice.none": ["Noch keine Übungen", "Aún no hay ejercicios"],
  "practice.none_text": ["Das Inhaltspaket enthält keine Übungen.", "El paquete de contenidos no tiene ejercicios."],
  "practice.listen": ["Hörtext üben", "Practicar audio"],
  "practice.listen_n": [(n) => `${n} Hörtexte`, (n) => `${n} audios`],
  "practice.read": ["Lesetext üben", "Practicar lectura"],
  "practice.read_n": [(n) => `${n} Lesetexte`, (n) => `${n} textos`],
  "practice.texts": ["Hören und Lesen", "Escuchar y leer"],
  "practice.texts_text": ["Der nächste Text auf deinem Niveau, den du noch nicht geübt hast. Hören kommt in den Sessions nur dosiert vor; hier übst du es gezielt.",
    "El siguiente texto de tu nivel que aún no has practicado. En las sesiones la comprensión auditiva aparece con moderación; aquí la practicas a propósito."],
  "practice.conversations": ["Gespräche", "Conversaciones"],
  "practice.conv_text": ["Ein echtes Gespräch über mehrere Runden, das auf deine Antworten eingeht – am besten gesprochen.",
    "Una conversación real de varias rondas que reacciona a tus respuestas; mejor si hablas."],
  "practice.done_n": [(n) => `${n}× geführt`, (n) => `${n} ${n === 1 ? "vez" : "veces"}`],
  "practice.paused": ["pausiert", "en pausa"],
  "practice.running": ["läuft", "en curso"],
  "practice.all_topics": ["Alle Themen", "Temas"],
  "practice.try_again": ["Noch einmal versuchen", "Intentarlo de nuevo"],
  "practice.skipped": ["Übersprungen. Das zählt nicht als Fehler.", "Saltado. No cuenta como error."],
  "practice.noted": ["Notiert: Das war heute noch schwer zu verstehen. Das zählt nicht als Fehler; wir üben es behutsamer.",
    "Anotado: hoy ha costado entenderlo. No cuenta como error; lo practicaremos con más calma."],
  "practice.again": ["Noch einmal", "Otra vez"],
  "practice.to_session": ["Zur geplanten Session", "Ir a la sesión planificada"],
  "practice.overview": ["Zur Übersicht", "Volver"],


  // ---------------------------------------------------------------- Fortschritt
  "locale": ["de-DE", "es-ES"],
  "progress.empty_text": ["Sobald du Übungen machst, siehst du hier, was sitzt, wo es hakt und welche Muster sich zeigen.",
    "En cuanto hagas ejercicios, aquí verás lo que dominas, dónde fallas y qué patrones aparecen."],
  "progress.first": ["Erste Session starten", "Empezar la primera sesión"],
  "progress.levels": ["Niveau je Bereich", "Nivel por área"],
  "progress.history": ["Entwicklung", "Evolución"],
  "progress.history_empty": ["Die Entwicklung erscheint nach der ersten Einstufung.", "La evolución aparece tras la primera prueba de nivel."],
  "progress.to_profile": ["Zum Sprachprofil", "Ver perfil de idioma"],
  "progress.listening": ["🎧 Hören", "🎧 Comprensión auditiva"],
  "progress.not_heard": ["Schriftlich sicher, beim Hören noch nicht geprüft: ", "Seguro por escrito, aún sin comprobar al oído: "],
  "progress.competence": ["Kompetenz", "Competencia"],
  "progress.production_empty": ["Freie und spontane Produktion erscheinen, sobald du Strukturen oder Ausdrücke geübt hast.",
    "La producción libre y espontánea aparece cuando hayas practicado estructuras o expresiones."],
  "progress.patterns": ["Deine häufigsten Muster", "Tus patrones más frecuentes"],
  "progress.not_enough": ["Noch nicht genügend Daten.", "Aún no hay datos suficientes."],
  "progress.overcome": ["Das sitzt inzwischen gut", "Esto ya lo dominas"],
  "progress.focus": ["Daran arbeiten wir gerade", "En esto trabajamos ahora"],
  "progress.more": [(n) => ` und ${n} weitere`, (n) => ` y ${n} más`],
  "progress.no_focus": ["Gerade kein besonderer Schwerpunkt.", "Ahora no hay un enfoque especial."],
  "progress.strengths": ["Stärken", "Puntos fuertes"],
  "progress.strengths_empty": ["Noch nicht genügend Daten. Stärken zeigen sich nach mehreren sicheren Anwendungen.",
    "Aún no hay datos suficientes. Los puntos fuertes aparecen tras varios usos seguros."],
  "progress.overview": ["Überblick", "Resumen"],
  "progress.days": ["Lerntage", "Días de estudio"],
  "progress.sessions": ["Sessions", "Sesiones"],
  "progress.streak": ["Serie", "Racha"],
  "progress.streak_value": [(n, r) => `${n} (Rekord ${r})`, (n, r) => `${n} (récord ${r})`],
  "progress.due": ["Wiederholung fällig", "Repasos pendientes"],
  "progress.mastered": ["Beherrscht", "Dominados"],


  // ---------------------------------------------------------------- Profil
  "profile.name": ["Wie soll dich die App nennen?", "¿Cómo quieres que te llame la app?"],
  "profile.ui_language": ["Sprache der App", "Idioma de la app"],
  "profile.explanations": ["Erklärungen auf", "Explicaciones en"],
  "profile.explanations_help": ["Gilt für alle Lernsprachen: Rückmeldungen, Grammatik- und Fehlererklärungen, „Warum?“ und „Was als Nächstes?“.",
    "Para todos los idiomas: correcciones, explicaciones de gramática y errores, «¿Por qué?» y «¿Qué sigue?»."],
  "profile.ai": [" KI-Zusatzanalyse (lokal)", " Análisis adicional con IA (local)"],
  "profile.ai_on": ["Ergänzt die Regelbewertung um unbestätigte Hinweise. Sie ändert weder Bewertung noch Lernstand und läuft nur auf diesem PC (einige Sekunden pro Antwort).",
    "Añade indicaciones sin confirmar a la evaluación por reglas. No cambia la evaluación ni el progreso y solo funciona en este PC (unos segundos por respuesta)."],
  "profile.ai_off": ["Nicht verfügbar: Dafür muss die App über „python main.py serve“ laufen und das lokale Sprachmodell bereitstehen (siehe docs/sprache.md).",
    "No disponible: la app debe ejecutarse con «python main.py serve» y el modelo de lenguaje local debe estar instalado (ver docs/sprache.md)."],
  "profile.backup": ["Sicherung herunterladen", "Descargar copia de seguridad"],
  "profile.backup_title": ["Sprachtrainer-Sicherung", "Copia de seguridad de Sprachtrainer"],
  "profile.backup_failed": ["Die Sicherung konnte nicht geteilt werden.", "No se ha podido compartir la copia de seguridad."],
  "profile.reset": ["Gerät zurücksetzen", "Restablecer el dispositivo"],
  "profile.reset_q": ["Gerät zurücksetzen?", "¿Restablecer el dispositivo?"],
  "profile.reset_text": [(n) => `Das löscht ALLE Nutzer auf diesem Gerät (${n}) mit ihrer gesamten Lernhistorie und allen Einstellungen. Das lässt sich nicht rückgängig machen. Einzelne Nutzer löschst du oben unter „Nutzer auf diesem Gerät“.`,
    (n) => `Esto borra TODOS los perfiles de este dispositivo (${n}) con su historial y sus ajustes. No se puede deshacer. Para borrar un solo perfil, usa «Perfiles en este dispositivo».`],
  "profile.reset_confirm": ["Alles löschen", "Borrar datos"],
  "profile.settings": [(name) => `Einstellungen für ${name}`, (name) => `Ajustes de ${name}`],
  "profile.data": ["Deine Daten", "Tus datos"],
  "profile.local": ["Alles bleibt lokal auf diesem Gerät. Nichts wird in eine Cloud geschickt.", "Tus datos se quedan en este dispositivo. No se envía nada a la nube."],
  "profile.entries": ["Einträge von dir", "Tus registros"],
  "profile.since": ["Seit", "Desde"],
  "profile.content_exercises": ["Übungen im Inhalt", "Ejercicios disponibles"],
  "profile.offline": ["Offline: ", "Sin conexión: "],
  "profile.evaluation": ["Bewertung: lokal, regelbasiert", "Evaluación: local, por reglas"],
  "profile.with_ai": [" + KI-Zusatzhinweise (lokal)", " + indicaciones de IA (local)"],
  "profile.without_ai": [" (ohne KI)", " (sin IA)"],
  "profile.speech": ["Spracheingabe: ", "Entrada de voz: "],
  "profile.speech_local": [(m) => `lokal (${m})`, (m) => `local (${m})`],
  "profile.unavailable": ["nicht verfügbar", "no disponible"],
  "profile.content_version": ["Inhaltsversion: ", "Versión de contenidos: "],
  "profile.debug": ["Entwicklersicht", "Vista de desarrollo"],
  "profile.add": ["Hinzufügen", "Añadir"],
  "profile.created": [(n) => `${n} wurde angelegt.`, (n) => `Se ha creado ${n}.`],
  "profile.create_failed": ["Konnte nicht angelegt werden.", "No se ha podido crear."],
  "profile.active": [" · aktiv", " · activo"],
  "profile.switch": ["Wechseln", "Cambiar"],
  "profile.delete_q": [(n) => `${n} löschen?`, (n) => `¿Borrar ${n}?`],
  "profile.delete_text": [(n) => `Das löscht ${n} und die gesamte Lernhistorie dieses Nutzers. Andere Nutzer sind nicht betroffen.`,
    (n) => `Esto borra ${n} y su historial. Los demás perfiles no se ven afectados.`],
  "profile.delete": ["Löschen", "Borrar"],
  "profile.users": ["Nutzer auf diesem Gerät", "Perfiles en este dispositivo"],
  "profile.users_text": ["Jeder Nutzer hat seinen eigenen Lernstand. Nichts wird geteilt.", "Cada perfil tiene su propio progreso. No se comparte nada."],
  "profile.languages": ["Lernsprachen", "Idiomas"],
  "profile.learning_now": ["Du lernst gerade ", "Ahora aprendes "],
  "profile.learning_now_end": [". Jede Sprache hat ihren eigenen Lernstand.", ". Cada idioma tiene su propio progreso."],
  "profile.language_profile": ["Sprachprofil", "Perfil de idioma"],


  // ---------------------------------------------------------------- Sprachen und Sprachprofil
  "languages.title": ["Meine Sprachen", "Mis idiomas"],
  "languages.lead": ["Jede Sprache hat ihren eigenen Lernstand. Nichts wird zwischen Sprachen vermischt.", "Cada idioma tiene su propio progreso. No se mezcla nada entre idiomas."],
  "languages.range": [(a, b) => ` · Ziel ${a}–${b}`, (a, b) => ` · Nivel ${a}–${b}`],
  "languages.reassess": ["Einstufung wiederholen", "Repetir la prueba de nivel"],
  "languages.assess": ["Einstufung starten", "Hacer la prueba de nivel"],
  "languages.active": ["Aktiv", "Activo"],
  "languages.open": ["Öffnen", "Abrir"],
  "languages.mine": ["Du lernst", "Aprendes"],
  "languages.add": ["Sprache hinzufügen", "Añadir idioma"],
  "languages.note": [" Inhalte werden je Sprache eigens erstellt und geprüft, nicht maschinell übersetzt. Deshalb kommen neue Sprachen nach und nach.",
    " Los contenidos se crean y revisan para cada idioma, sin traducción automática. Por eso los idiomas nuevos llegan poco a poco."],
  "lp.title": [(n) => `Sprachprofil ${n}`, (n) => `Perfil de ${n.toLowerCase()}`],
  "lp.lead": ["Geschätzt aus allen deinen Übungen, Gesprächen, Sprachaufnahmen und Einstufungen in dieser Sprache.",
    "Estimado a partir de tus ejercicios, conversaciones, grabaciones y pruebas de nivel en este idioma."],
  "lp.overall": ["Gesamteinschätzung", "Estimación global"],
  "lp.basis": [(b) => `Grundlage: ${b}`, (b) => `Basado en: ${b}`],
  "lp.self": [(l) => `Deine Selbsteinschätzung: ${l} (fließt nicht in die Schätzung ein)`, (l) => `Tu autoevaluación: ${l} (no influye en la estimación)`],
  "lp.dimensions": ["Bereiche", "Áreas"],
  "lp.evidence": [(n, a, p) => ` · ${n} Nachweise (${a} Einstufung, ${p} Übung)`, (n, a, p) => ` · ${n} datos (${a} de la prueba, ${p} de ejercicios)`],
  "lp.sw": ["Stärken und Schwächen", "Puntos fuertes y débiles"],
  "lp.stronger": [" Stärker: ", " Más fuerte: "],
  "lp.working": [" Daran arbeitet deine Planung gezielt: ", " Tu plan trabaja en esto: "],
  "lp.vocabulary": ["Wortschatz", "Vocabulario"],
  "lp.vocab_active": [(a, s) => `${a} Ausdrücke aktiv genutzt, davon ${s} sicher.`, (a, s) => `${a} expresiones usadas activamente, ${s} con seguridad.`],
  "lp.size_note": ["Wortschatzgröße noch nicht schätzbar: Dafür fehlen Wortlisten nach Häufigkeit im Inhalt.",
    "Aún no se puede estimar el tamaño del vocabulario: faltan listas de frecuencia en los contenidos."],
  "lp.history": ["Verlauf", "Historial"],
  "lp.history_empty": ["Noch keine Einstufung. Nach jeder Einstufung wird hier der Stand festgehalten.", "Aún no hay prueba de nivel. Tras cada prueba, aquí se guarda el resultado."],
  "lp.next": [(d, r) => `Nächste Neubewertung: ${d} (${r})`, (d, r) => `Próxima reevaluación: ${d} (${r})`],
  "lp.trigger_time": [(d) => `nach ${d} Tagen neu einstufen`, (d) => `nueva prueba tras ${d} días`],
  "lp.trigger_events": [(n) => `${n} neue Antworten seit der letzten Einstufung`, (n) => `${n} respuestas nuevas desde la última prueba`],
  "lp.trigger_shift": [(s) => `Gesamtschätzung hat sich um ${s} verändert`, (s) => `la estimación global ha cambiado ${s}`],
  "lp.trigger_none": ["noch keine Einstufung", "aún sin prueba de nivel"],
  "lp.gaps": [(g) => `Noch nicht messbar: ${g}. Dafür fehlen noch Aufgaben im Sprachpaket.`, (g) => `Aún no se puede medir: ${g}. Faltan tareas en el paquete de idioma.`],


  // ---------------------------------------------------------------- Einstufung
  "as.title": [(n) => `Einstufung ${n}`, (n) => `Prueba de nivel de ${n.toLowerCase()}`],
  "as.none": ["Für diese Sprache gibt es noch keine Einstufungsaufgaben. Sie folgen mit dem Inhaltspaket.",
    "Aún no hay tareas de prueba de nivel para este idioma. Llegarán con su paquete de contenidos."],
  "as.start_failed": ["Die Einstufung konnte nicht gestartet werden.", "No se ha podido iniciar la prueba de nivel."],
  "as.self_q": ["Wie schätzt du dein Niveau ein? Das ist nur der Startpunkt, nicht das Ergebnis: Die App passt die Aufgaben an deine Antworten an.",
    "¿Qué nivel crees que tienes? Es solo el punto de partida, no el resultado: la app adapta las tareas a tus respuestas."],
  "as.self": ["Selbsteinschätzung", "Autoevaluación"],
  "as.intro": [(areas) => `Etwa 10–15 Minuten · Bereiche: ${areas}. Du kannst jederzeit pausieren. „Weiß ich nicht“ ist besser als Raten.`,
    (areas) => `Unos 10–15 minutos · Áreas: ${areas}. Puedes pausar cuando quieras. «No lo sé» es mejor que adivinar.`],
  "as.gaps": [(g) => `Noch nicht messbar: ${g} (keine Aufgaben in diesem Sprachpaket).`, (g) => `Aún no se puede medir: ${g} (no hay tareas en este paquete).`],
  "as.pause": ["Pausieren", "Pausar"],
  "as.abandon_q": ["Einstufung abbrechen?", "¿Cancelar la prueba de nivel?"],
  "as.abandon_text": ["Deine bisherigen Antworten bleiben gespeichert und fließen ins Sprachprofil ein.", "Tus respuestas quedan guardadas y se tienen en cuenta en tu perfil de idioma."],
  "as.keep": ["Weitermachen", "Seguir"],
  "as.module_of": [(i, n) => `Bereich ${i} von ${n}`, (i, n) => `Área ${i} de ${n}`],
  "as.progress": ["Fortschritt der Einstufung", "Progreso de la prueba"],
  "as.evaluating": ["Wird ausgewertet …", "Evaluando …"],
  "as.paused_text": ["Deine Antworten sind gespeichert. Es geht mit dem nächsten Bereich weiter.", "Tus respuestas están guardadas. Seguirás con la siguiente área."],
  "as.abandoned": ["Einstufung abgebrochen", "Prueba de nivel cancelada"],
  "as.done": ["Einstufung abgeschlossen", "Prueba de nivel completada"],
  "as.disclaimer": ["Das ist eine Schätzung aus wenigen, von Hand eingestuften Aufgaben, keine geprüfte Zertifizierung. Mit jeder Übung, jedem Gespräch und jeder Sprachaufnahme wird dein Sprachprofil genauer.",
    "Es una estimación a partir de pocas tareas clasificadas a mano, no una certificación oficial. Con cada ejercicio, conversación y grabación tu perfil se vuelve más preciso."],
  "as.where": ["Wo stehst du?", "¿Dónde estás?"],
  "as.not_measured": ["noch nicht gemessen", "aún sin medir"],
  "as.next": ["Was als Nächstes?", "¿Qué sigue?"],
  "as.dont_know": ["Weiß ich nicht", "No lo sé"],
  "as.skip_module": ["Ohne Mikrofon: diesen Bereich auslassen", "Sin micrófono: saltar esta área"],
  "as.continue": ["Weiter", "Continuar"],


  // ---------------------------------------------------------------- Gespräch
  "conv.your_turn": ["Du bist dran: tippe oder sprich deine Antwort.", "Te toca: escribe o di tu respuesta."],
  "conv.recording": ["Aufnahme läuft …", "Grabando …"],
  "conv.evaluating": ["Antwort wird ausgewertet …", "Evaluando la respuesta …"],
  "conv.stt_error": ["Die Spracherkennung hat nicht geklappt. Versuche es noch einmal oder tippe.", "El reconocimiento de voz ha fallado. Inténtalo otra vez o escribe."],
  "conv.empty": ["Sag oder schreib zuerst etwas.", "Primero di o escribe algo."],
  "conv.paused_status": ["Das Gespräch ist pausiert.", "La conversación está en pausa."],
  "conv.ai_unavailable": ["Die KI-Hilfe ist gerade nicht erreichbar. Das Gespräch läuft ohne sie weiter.", "La ayuda de IA no está disponible. La conversación sigue sin ella."],
  "conv.time_up": ["Die Zeit ist fast um: letzte Frage.", "Se acaba el tiempo: última pregunta."],
  "conv.ai_timeout": ["Die KI-Hilfe hat zu lange gebraucht. Das Gespräch läuft ohne sie weiter.", "La ayuda de IA ha tardado demasiado. La conversación sigue sin ella."],
  "conv.all": ["Alle Gespräche", "Conversaciones"],
  "conv.start": ["Gespräch beginnen", "Empezar la conversación"],
  "conv.start_failed": ["Das Gespräch konnte nicht gestartet werden.", "No se ha podido iniciar la conversación."],
  "conv.goal": ["Dein Ziel: ", "Tu objetivo: "],
  "conv.partner": ["Gesprächspartner: ", "Interlocutor: "],
  "conv.intro": ["Antworte schriftlich oder sprich. Während des Gesprächs gibt es keine Fehlerliste; die Auswertung kommt am Ende.",
    "Responde por escrito o hablando. Durante la conversación no hay lista de errores; la evaluación llega al final."],
  "conv.other_open": [(title) => `Du hast noch ein offenes Gespräch: „${title}“. Es ist immer nur eines offen.`,
    (title) => `Tienes otra conversación abierta: «${title}». Solo puede haber una abierta.`],
  "conv.continue_there": ["Dort weitermachen", "Continuar allí"],
  "conv.duration": ["Dauer", "Duración"],
  "conv.last_result": ["Letzte Auswertung", "Última evaluación"],
  "conv.pause_failed": ["Das Gespräch konnte nicht pausiert werden.", "No se ha podido pausar la conversación."],
  "conv.round": [(r, m, b) => `Runde ${r} · noch etwa ${m} von ${b} Min.`, (r, m, b) => `Ronda ${r} · quedan unos ${m} de ${b} min`],
  "conv.time_used": ["Verbrauchte Gesprächszeit", "Tiempo de conversación usado"],
  "conv.transcript": ["Gesprächsverlauf", "Transcripción"],
  "conv.resume_failed": ["Das Gespräch konnte nicht fortgesetzt werden.", "No se ha podido continuar la conversación."],
  "conv.paused_text": ["Die Pausenzeit zählt nicht zur Gesprächszeit. Die letzte Frage wartet auf dich.", "El tiempo en pausa no cuenta. La última pregunta te espera."],
  "conv.end_q": ["Gespräch beenden?", "¿Terminar la conversación?"],
  "conv.end_text": ["Deine bisherigen Antworten bleiben gespeichert und fließen in die Auswertung ein.", "Tus respuestas quedan guardadas y se tienen en cuenta en la evaluación."],
  "conv.keep": ["Weiterreden", "Seguir hablando"],
  "conv.end_failed": ["Das Gespräch konnte nicht beendet werden.", "No se ha podido terminar la conversación."],
  "conv.again": ["Noch einmal führen", "Repetir la conversación"],
  "conv.ended": ["Gespräch beendet", "Conversación terminada"],
  "conv.completed": ["Gespräch abgeschlossen!", "¡Conversación completada!"],
  "conv.to_list": ["Zu den Gesprächen", "Ver conversaciones"],
  "conv.minutes": ["Minuten", "Minutos"],
  "conv.rounds": ["Runden", "Rondas"],
  "conv.spoken": ["gesprochen", "habladas"],
  "conv.error_free": ["ohne Fehler", "sin errores"],
  "conv.went_well": ["Was gut lief", "Lo que salió bien"],
  "conv.work_on": ["Woran wir arbeiten", "En qué trabajamos"],
  "conv.natural": ["Ein Satz, den du so sagen könntest", "Una frase que podrías decir así"],
  "conv.original": ["Original", "Original"],
  "conv.ai_suggestion": ["Vorschlag der lokalen KI (unbestätigt)", "Propuesta de la IA local (sin confirmar)"],
  "conv.better": ["Besser", "Mejor"],
  "conv.goal_opinion": ["Meinung", "Opinión"],
  "conv.goal_discussion": ["Diskussion", "Debate"],
  "conv.goal_problem_solving": ["Problemlösung", "Resolver un problema"],
  "conv.goal_everyday": ["Alltag", "Día a día"],
  "conv.goal_professional": ["Beruf", "Trabajo"],
  "conv.goal_spontaneous": ["Spontan", "Espontánea"],
  "conv.done_goal_reached": ["Gesprächsziel erreicht", "Objetivo de la conversación cumplido"],
  "conv.done_time_budget": ["Zeit abgelaufen, Gespräch abgerundet", "Se acabó el tiempo; conversación cerrada"],
  "conv.done_max_turns": ["alle Runden geführt", "todas las rondas hechas"],
  "conv.done_abandoned": ["Gespräch vorzeitig beendet", "Conversación terminada antes de tiempo"],
  "conv.well_done": [(label) => `Gut umgesetzt: ${label}`, (label) => `Bien aplicado: ${label}`],


  // ---------------------------------------------------------------- Modelle: Bedarf, Fortschritt, Niveau
  "need.reviews": [(n) => `${n} ${n === 1 ? "Wiederholung" : "Wiederholungen"} fällig`, (n) => `${n} ${n === 1 ? "repaso pendiente" : "repasos pendientes"}`],
  "need.recurring": [(n) => `${n} ${n === 1 ? "wiederkehrender Fehler" : "wiederkehrende Fehler"}`, (n) => `${n} ${n === 1 ? "error recurrente" : "errores recurrentes"}`],
  "need.production": [(n) => `${n} ${n === 1 ? "Lücke" : "Lücken"} in der freien Produktion`, (n) => `${n} ${n === 1 ? "laguna" : "lagunas"} en la producción libre`],
  "need.avoided": [(n) => `${n} ${n === 1 ? "Struktur" : "Strukturen"}, die du oft umgehst`, (n) => `${n} ${n === 1 ? "estructura que" : "estructuras que"} sueles evitar`],
  "area.grammar": ["Grammatik", "Gramática"],
  "area.vocabulary": ["Wortschatz", "Vocabulario"],
  "area.errors": ["Typische Fehler vermeiden", "Evitar errores típicos"],
  "area.detail": [(s, b, n) => `${s} gefestigt · ${b} begonnen · ${n} insgesamt`, (s, b, n) => `${s} afianzados · ${b} empezados · ${n} en total`],
  "area.no_content": ["noch keine Inhalte", "aún sin contenidos"],
  "area.free": ["Freie Produktion", "Producción libre"],
  "area.free_detail": [(f, n) => `${f} von ${n} geübten Strukturen und Ausdrücken frei verwendet`, (f, n) => `${f} de ${n} estructuras y expresiones practicadas usadas con libertad`],
  "area.spontaneous": ["Spontane Kommunikation", "Comunicación espontánea"],
  "area.spontaneous_detail": [(s, n) => `${s} von ${n} spontan im Gespräch verwendet`, (s, n) => `${s} de ${n} usadas espontáneamente al conversar`],
  "rec.start_diagnostic": ["Standortbestimmung starten", "Empezar con una evaluación inicial"],
  "rec.focus_error_elimination": ["Fehler gezielt abbauen", "Eliminar errores de forma específica"],
  "rec.increase_production_difficulty": ["Schwierigkeit der Produktion steigern", "Aumentar la dificultad de la producción"],
  "rec.focus_lexical_activation": ["Wortschatz aktivieren", "Activar el vocabulario"],
  "rec.move_to_spontaneous_production": ["Zur spontanen Produktion übergehen", "Pasar a la producción espontánea"],
  "rec.continue_reinforcement": ["Weiter festigen", "Seguir afianzando"],
  "progress.patterns_empty": ["Noch nicht genügend Daten für wiederkehrende Muster.", "Aún no hay datos suficientes para detectar patrones."],
  "progress.strengths_days": ["Stärken zeigen sich, wenn du an mehreren Tagen geübt hast.", "Los puntos fuertes aparecen cuando hayas practicado varios días."],
  "progress.headline_none": ["Noch keine Übungen in dieser Sprache. Deine erste Session legt los.", "Aún no hay ejercicios en este idioma. Tu primera sesión da el pistoletazo de salida."],
  "progress.headline": [(n, f, e) => `${n === 1 ? "1 Struktur oder Ausdruck" : `${n} Strukturen und Ausdrücke`} geübt, davon ${f} schon frei verwendet.${e ? ` ${e === 1 ? "Ein typischer Fehler kommt" : `${e} typische Fehler kommen`} noch vor.` : ""}`,
    (n, f, e) => `${n === 1 ? "1 estructura o expresión practicada" : `${n} estructuras y expresiones practicadas`}, ${f} ya usadas con libertad.${e ? ` ${e === 1 ? "Aún aparece un error típico" : `Aún aparecen ${e} errores típicos`}.` : ""}`],
  "claim.insufficient": ["zu wenig Daten für eine Einschätzung", "pocos datos para una estimación"],
  "claim.about": [(l) => `etwa ${l}`, (l) => `aprox. ${l}`],
  "claim.low": ["geringe Sicherheit, vorläufig", "fiabilidad baja, provisional"],
  "claim.medium": ["mittlere Sicherheit", "fiabilidad media"],
  "claim.high": ["hohe Sicherheit", "fiabilidad alta"],
  "claim.none": ["noch nicht einschätzbar", "aún sin estimar"],
  "claim.no_tasks": ["noch nicht messbar (keine Aufgaben in diesem Sprachpaket)", "aún no se puede medir (no hay tareas en este paquete)"],
  "dim.grammar": ["Grammatik", "Gramática"],
  "dim.vocabulary": ["Wortschatz", "Vocabulario"],
  "dim.reading": ["Leseverstehen", "Comprensión lectora"],
  "dim.listening": ["Hörverstehen", "Comprensión auditiva"],
  "dim.production": ["Schreiben", "Expresión escrita"],
  "dim.conversation": ["Sprechen im Gespräch", "Conversación"],
  "module.pending": ["offen", "pendiente"],
  "module.in_progress": ["läuft", "en curso"],
  "module.done": ["erledigt", "hecho"],
  "module.skipped": ["ausgelassen", "omitido"],
  "module.unavailable": ["noch keine Aufgaben", "aún sin tareas"],


  // ---------------------------------------------------------------- Hören (Anzeige)
  "support.keywords": ["Stichwörter zeigen", "Mostrar palabras clave"],
  "support.partial_transcript": ["Teil des Textes zeigen", "Mostrar parte del texto"],
  "support.full_transcript": ["Ganzen Text zeigen", "Mostrar el texto completo"],
  "source.real": ["echte Aufnahme", "grabación real"],
  "source.synthetic": ["synthetische Aufnahme (Sprachausgabe)", "grabación sintética (voz artificial)"],
  "listen.section": ["Abschnitt", "Fragmento"],
  "listen.section_n": [(n) => `Abschnitt ${n}`, (n) => `Fragmento ${n}`],
  "listen.question_of": [(i, n) => `Frage ${i} von ${n} zu diesem Hörtext`, (i, n) => `Pregunta ${i} de ${n} sobre este audio`],
  "listen.length_short": ["kurzer Hörtext", "audio corto"],
  "listen.length_medium": ["mittellanger Hörtext", "audio de longitud media"],
  "listen.length_long": ["langer Hörtext", "audio largo"],
  "listen.so_far": [(s) => `In deinen bisherigen Höraufgaben: ${s}`, (s) => `En tus ejercicios de audio hasta ahora: ${s}`],
  "listen.none": ["Du hast noch keine Höraufgabe gemacht. Hören ist deshalb nicht gemessen, nicht schwach.",
    "Aún no has hecho ejercicios de audio. Por eso la comprensión auditiva no está medida, no es débil."],
  "listen.weak_written": ["Schriftlich sicher, im Gesprochenen noch nicht sicher erkannt.", "Seguro por escrito, aún no reconocido con seguridad al oído."],
  "listen.weak": ["Beim Hören noch unsicher.", "Aún inseguro al escuchar."],
  "listen.avoidance": ["Höraufgaben wurden zuletzt oft übersprungen. Wir fangen mit kürzeren, langsameren Aufnahmen an.",
    "Últimamente has saltado a menudo los audios. Empezamos con grabaciones más cortas y lentas."],
  "listen.note": ["Gemessen wird bisher vor allem das Verstehen kurzer Sätze, noch kein natürliches Hörverstehen längerer Gespräche.",
    "Por ahora se mide principalmente la comprensión de frases cortas, aún no la de conversaciones largas y naturales."],
  "lstate.unverified": ["noch nicht geprüft", "aún sin comprobar"],
  "lstate.supported": ["bisher nur mit Hilfe gehört", "hasta ahora solo con ayuda"],
  "lstate.insufficient_evidence": ["noch zu wenige Antworten", "aún pocas respuestas"],
  "lstate.developing": ["im Aufbau", "en desarrollo"],
  "lstate.verified": ["sicher (in den geprüften Aufgaben)", "seguro (en los ejercicios comprobados)"],
  "lstate.weak": ["noch nicht sicher verstanden", "aún no entendido con seguridad"],
  "lmode.sentence_comprehension": ["Satz verstehen", "Entender la frase"],
  "lmode.contextual_comprehension": ["Hörtext verstehen", "Entender el audio"],
  "lmode.contextual_inference": ["aus dem Hörtext schließen", "deducir del audio"],
  "lmode.inference": ["schließen", "deducir"],
  "lmode.discourse": ["Zusammenhang verstehen", "entender la relación"],
  "lmode.speaker_recognition": ["Sprecher unterscheiden", "distinguir hablantes"],
  "lmode.dictation": ["Diktat", "Dictado"],
  "lmode.response": ["auf das Gehörte antworten", "responder a lo escuchado"],
  "measure.global": ["Hauptaussage", "Idea principal"],
  "measure.detail": ["Details", "Detalles"],
  "measure.inference": ["Schlussfolgern", "Inferencia"],
  "measure.vocabulary": ["Bedeutung im Kontext", "Significado en contexto"],
  "measure.attitude": ["Absicht des Sprechers", "Intención del hablante"],
  "measure.style": ["Ton und Register", "Tono y registro"],
  "measure.lexical_recognition": ["Wörter erkennen", "Reconocer palabras"],
  "measure.grammatical_recognition": ["Formen erkennen", "Reconocer formas"],
  "measure.discrimination": ["ähnliche Formen unterscheiden", "distinguir formas parecidas"],
  "measure.dictation": ["Gehörtes aufschreiben", "Escribir lo escuchado"],
  "measure.sequence": ["Reihenfolge", "Orden"],
  "measure.discourse": ["Zusammenhang verstehen", "Entender la relación"],
  "measure.speaker": ["Sprecher unterscheiden", "Distinguir hablantes"],


  // ---------------------------------------------------------------- Fehlermeldungen (nach Code)
  "err.unknown_user": [undefined, "Este perfil no existe."],
  "err.session_open": [undefined, "Ya hay una sesión en curso. Continúala o termínala primero."],
  "err.empty_plan": [undefined, "Ahora no hay ejercicios adecuados para esta duración."],
  "err.session_not_active": [undefined, "Esta sesión no está activa."],
  "err.unknown_topic": [undefined, "Este tema no existe."],
  "err.not_listening": [undefined, "Este no es un ejercicio de audio."],
  "err.invalid_reason": [undefined, "Motivo desconocido."],
  "err.unknown_scenario": [undefined, "Esta conversación no existe en los contenidos actuales."],
  "err.conversation_paused": [undefined, "La conversación está en pausa. Continúala primero."],
  "err.conversation_not_active": [undefined, "Esta conversación ya ha terminado."],
  "err.assessment_wrong_item": [undefined, "Esta tarea no toca ahora."],
  "err.unknown_exercise": [undefined, "Este ejercicio ya no está en los contenidos actuales."],
  "err.empty_answer": [undefined, "Primero escribe una respuesta."],
  "err.session_transition": [undefined, "No es posible en este estado de la sesión."],
  "err.invalid_input_mode": [undefined, "Tipo de entrada desconocido."],
  "err.empty_name": [undefined, "Escribe un nombre."],
  "err.duplicate_name": [undefined, "Ya existe un perfil con ese nombre."],
  "err.active_user": [undefined, "El perfil activo no se puede borrar. Cambia antes a otro perfil."],
  "err.unknown_language": [undefined, "Aún no aprendes este idioma. Añádelo primero."],
  "err.invalid_goal": [undefined, "Objetivo diario: elige 5, 10, 15, 20 o 30 minutos."],
  "err.invalid_explanation_language": [undefined, "Idioma de las explicaciones: alemán o español."],
  "err.invalid_ui_language": [undefined, "Idioma de la app: alemán o español."],
  "err.invalid_level": [undefined, "Elige un nivel de A1 a C2."],
  "err.paused": [undefined, "La prueba de nivel está en pausa."],
  "err.already_active": [undefined, "Ya hay una prueba de nivel en curso."],
  "err.no_content": [undefined, "Aún no hay tareas de prueba de nivel para este idioma."],
  "err.unknown_assessment": [undefined, "Esta prueba de nivel no existe."],
  "err.wrong_module": [undefined, "Esta área no está abierta."],
  "err.wrong_item": [undefined, "Esta tarea no toca ahora."],


  "pattern.recurring_error": ["Dieser Fehler kommt wiederholt vor.", "Este error aparece de forma repetida."],
  "pattern.production_gap": ["Kontrolliert sicher, frei noch nicht.", "Lo dominas de forma guiada, pero aún no con libertad."],
  "pattern.avoided_structure": ["Wird oft umgangen, obwohl verlangt.", "A menudo lo evitas aunque se pida."],
  "pattern.stable_strength": ["Sitzt sicher.", "Lo dominas con seguridad."],
  "pattern.auditory_recognition_gap": ["Schriftlich sicher, beim Hören noch nicht erkannt.", "Seguro por escrito, aún no lo reconoces al oído."],

});
